### ISSUE TITLE
Outreach to "Influencers" for FACN3 application

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#21]
Can each of you think of at least one person with a substantial following (doesn't have to be in tech) that you could contact about the application? We'd ideally like this person to repost our first post (coming as soon as the website is up) and then repost other graphics 2x/week for the next 4 weeks.

For example, you probably know [Hasan Abo-Shally](https://www.facebook.com/hasan.aboshally.5), followed by nearly 9000 people, and [Donna Haj](https://www.facebook.com/donna.haj.7).

There are plenty of others, especially in other fields, dig around and post what you find!

**Comment by HilbertSpitzer** [comment]
I know her, she's a TV host: https://www.facebook.com/ruba.warwar
And by that I mean that I actually know her from childhood. She has +6,000 followers and I can actually meet her eye-to-eye, I haven't met her in a long time but I'm fairly certain I'm on good terms with her and that she'll be kind and supportive with this (even if we don't have much to give)

I could go ahead and act on my own if you really want me to
But I would like it if you could elaborate a bit more. What exactly do you want to advertise? Or would you prefer that I just go ahead and ask her(Ruba) about the best way to advertise ourselves?

She's [influential enough](http://www.sonara.net/full/202247/%D8%A8%D9%8A%D8%B1%D8%B3-%D9%8A%D9%85%D9%86%D8%AD-%D8%A7%D9%84%D8%A7%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D8%B1%D8%A8%D9%89-%D9%88%D8%B1%D9%88%D8%B1-%D9%88%D8%B3%D8%A7%D9%85-%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3-%D9%84%D9%84%D9%85%D8%AA%D8%B7%D9%88%D8%B9) to meet with [former Israeli President Shimon Peres](http://images.sonara.net/20140623-81104860604809.jpg), and to even be the only Arab among 12 to be awarded the [Presidential Volunteer Medal](http://blinker.co.il/%D7%A2%D7%9E%D7%A7%D7%99%D7%9D/%D7%A0%D7%A6%D7%A8%D7%AA/%D7%A2%D7%99%D7%AA%D7%95%D7%A0%D7%90%D7%99%D7%AA-%D7%9E%D7%A0%D7%A6%D7%A8%D7%AA-%D7%A7%D7%99%D7%91%D7%9C%D7%94-%D7%90%D7%AA-%D7%90%D7%95%D7%AA-%D7%94%D7%A0%D7%A9%D7%99%D7%90-%D7%9C%D7%9E%D7%AA%D7%A0/56709/), I think this has potential
http://yomnet.net/?page=News&id=41998
> "حصلت على وسام رئيس الدولة للمتطوع من قبل رئيس الدولة السابق شمعون بيرس وكنت العربية الوحيدة من بين 12 مكرم منحت لهم هذه الجائزة"

http://farfesh.net/Katavoot/Sneak/Html/1119.asp

**Comment by rebeccaradding** [comment]
@HilbertSpitzer great contact, and great questions. I'm pretty new to marketing/social media, but here's what I would suggest:

- Reach out to her and arrange to meet in person (if she can't meet sometime in the next week, ask if she has time to speak on the phone)
- Tell her about your experience with Founders & Coders and why joining FAC is a great opportunity 
- Briefly explain our current application process (short written application, interview, weekly 8 week prep course)
- Ask her if she has any friends/family who would be good candidates
- _Ask her to share our FB posts about the application at least once/week for the next four weeks, and to encourage people to apply_
- Ask her _how else_ she thinks we can get the word out to our target audience (everyone over 18 interested in web development/who wants to work in tech - even without a technical background)

**Comment by HilbertSpitzer** [comment]
Alright, I'll almost certainly be meeting with her eye-to eye today, probably around ~+16:00(Nazareth time, which is GMT+2), if anyone wants to add anything, now would be a good time.

I just thought to ask since you know the inner workings of FAC way better than me, so perhaps you think there are certain videos that I should show her or that Dan has something to add or that some students already compiled a list of things (eg "experience with Founders & Coders") that you think could help out with this. Though perhaps I should just use my own words.

Regardless of your experience it's still better than mine and you're still capable of taking in an eloquent manner that I can't imitate. You didn't at all give the impression that you're new to this. Hopefully this will become more apparent if you'll gain more influence.

**Comment by rebeccaradding** [comment]
@HilbertSpitzer I look forward to hearing how it goes! Your personal experience is the most important thing you can talk about. 

When @sofer and I are in Nazareth how about we talk more about "representing FAC" and answer any questions you have on that topic?

**Comment by HilbertSpitzer** [comment]
> When @sofer and I are in Nazareth how about we talk more about "representing FAC" and answer any questions you have on that topic?

DO I have to actualy prepare questions? Aren't there guidelines or some presentation or sth that's already ready to give?

Anyway, my discussion with Rubba here will all be an approximate translation from Arabic, the below is all sth that Rubba said, albeit in my own words(so do as I say, not as I do):

The priorities of what we should focus on when advertising ourselves should have this ranking:
1. High-level Academic training by the personal companionship of specialized mentors from differing backgrounds
2. Free Education and the availability of low-cost lodging accommodation
3. The option for students to affect what gets taught and how. You can even get the chance to be a mentor and become a partner in deciding the learning environment
4. You get to enjoy an educational experience beyond academic materials by enjoying the cultural delight of being a part of a community of students and teachers from all over the world (we should also put emphasis here that the locals can do so without actually needing to go elsewhere abroad)

The image that we use to advertise ourselves should be:
- In the advertisement, the text of the qualitative image(a MUST) must be short, easy, clear, and straight to the point. The name of the organization should also be inside the text. It should also be multi-lingual, and yes, we do need this. And the simpler the advertisement is the better.
And even if you want to include an advertisement that is funky and amusing it’s still going to be secondary(unless if we’re changing the context and talking about a newspaper?) and it must share these qualities
1. perhaps by a link to the application page(for clarity on what we want)
2. or by being used along with the advertisement image that is more straight to the point(ie, we'll use both images)
3. or perhaps through the usage of a teaser (eg clicking on “curious about coding?” would change the image into a different image that would give the user more details about the application)
4. or by using an amusing image on week 2 then switching to the “straight to the point” image on week 3 and so on.
- MUST have the equivalent to an “apply now” text, you must make it clear what you want the potential applicants to do next. The one applying for the course should also be able to easily tell how to get to the application page, ie, you need to give the link together with the advertisement for the image, preferably, a mere click on the image would take you to the right page. This is very important and is used in a marketing technique called [“Call to Action (CTA)”](http://www.investopedia.com/terms/c/call-action-cta.asp). I’ve seen that some of our facebook advertisers did not do this, this is not good, fix it! And remember this for next time!
- Tell your facebook advertisers to change the advertising image they use for you once every week till the deadline of the application. Ideally, all of the FB users would do this on the same day and on the same time even. This will make us more relevant and impactful as opposed to being perceived as just a one-time small fad thing. Attempting to stay relevant will make potential applicants more likely to start wondering about what is this thing that keeps coming back
- Don’t use something that doesn’t quite fit the image of high-tech of progress into modernity, like a run-down chair. Remember that you're also advertising high-tech, not just FAC


another points to make:
- I just noticed that Tsofen didn't use fac's advertising images, only this: https://www.facebook.com/tsofentech/photos/a.153465384683983.30750.150003831696805/1565642326799608/?type=3&theater
This is no good, Tsofen is a very important ally, someone must tell them to use our advertisement images and give them the link to our application: https://foundersandcoders.com/apply/nazareth
This isn’t just me saying this, we need to give the students an answer to what they will be getting out of the course, and if Tsofen who is already a recognized part of the computing world would recommend FAC then it will make a difference, stressing that we’re working with Tsofen is a must, gives us some legitimacy and credibility don’t ya think? And using something that already has more popularity will likely make its popularity trinkle down on FAC too.
Or rather, Rubba recommends us to put an emphasis that we're working with Tsofen. It's interesting how she thinks this is what we should stress as opposed to Microsoft, perhaps I'm unqualified to talk to her about this because I don't really know what is the relationship between FAC and it's partners  


Not sure if we left the "let's use facebook to advertise ourselves" thing already, but I was thinking of trying to persuade these users to advertise us since Rubba recommended them:
https://www.facebook.com/nyassin14
https://www.facebook.com/hanin.majadli
https://www.facebook.com/profile.php?id=100001888167171
https://www.facebook.com/adi.khalefaii.5


To be continued?

**Comment by rebeccaradding** [comment]
@HilbertSpitzer these tips from Rubba are incredibly helpful. I'm going to read them more thoroughly and compile them into a file for outreach/marketing guidance, so that we are prepared to be more strategic in the future. I'm excited to talk more about what you learned in person!

Love the idea of reaching out to the influential users - do you want to do this or do you want to work someone on it?

**Comment by HilbertSpitzer** [comment]
> Love the idea of reaching out to the influential users

Haha, well, that was your idea in the first place! I was just making sure FAC is still fine with this

> do you want to do this or do you want to work someone on it?

If there is someone who is confident that he can do the job done then I would really appreciate it if said person could work on it instead. I think I'll wait for a few days, if there's nobody volunteering then I'll see what I can do
