### ISSUE TITLE
Reaching un- and under-employed candidates

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#9]
Al Fanar/Rayan
Contact in Nazareth: Reem Zoaby 
Email: reem.za@ec4u.org.il 

This is a very important potential relationship, as she is connected to a wider network of employment centers with lots of data on who is looking for re-training and in what areas. 

Please post updates on progress with her in this issue.

**Comment by esraajb** [comment]
No answer. 
Messaged her via Whatsapp.

**Comment by rebeccaradding** [comment]
@esraajb any luck here?

**Comment by esraajb** [comment]
Nope.
She didnt call back.

**Comment by HilbertSpitzer** [comment]
Let me jump right in,
as weird as it sounds, can you tell me what you know about Reem Zoaby?
Tell me her age and some central things about her, eg "her job is this and that"

**Comment by rebeccaradding** [comment]
@HilbertSpitzer 

@sofer and I have met her once. Relatively young, professional women. Both @esraajb and Waleed have had a hard time getting ahold of her and have been unable to coordinate a visit to the course.

**Comment by HilbertSpitzer** [comment]
The reason why I asked you was because I wanted to confirm whether she's the same Reem Zoaby that I myself know, forgive me for saying this but what you said didn't help out with that, but it was still interesting you mentioned that
Rubba claims that yes, Reem Zoaby really is the person that I know(Rubba herself knows Reem Zoaby) and that she works at the kind of stuff that would help out with with getting jobs for the locals, after she said that I showed her [this site](http://economy.gov.il/Employment/UniquePopulation/ArabSector/Pages/CentersList.aspx) and asked if Reem Zoaby really works at this(to be frank Rebecca, I Would have liked it very much if you could have given me an idea where you even got Reem Zoaby's mail from), Rubba again confirmed that she does. According to Rubba, Reem Zoaby is "dying" to work with people like FAC and claims that the reason why you couldn't get in touch with her was only a matter of bad luck with timing
I can definitely get in touch with Reem Zoaby, but I'm not on good terms with her as much as I am with Rubba, infact, I barely know how Reem Zoaby looks like nowadays. But I'm fairly certain I'm not on bad terms with her and I myself trust Rubba's word that it is in Reem Zoaby's interest to get in touch with you, although I admit that I'm biased so objectively speaking I won't promise anything
What do you want me to tell Reem Zoaby? Take it into account that I can't sit and talk to her eye-to-eye for hours, it has to be sth that would only be for a few minutes. And I think that it's highly probable that I need to actually use something to convince her to "coordinate a visit to the course", for starters, what does that even mean?

**Comment by rebeccaradding** [comment]
@HilbertSpitzer Dona Haj from the UKITH connected us to Reem Zoaby last December. Dan and I visited her at her office in Nazareth and had what felt like a productive conversation. She sent us CVs for three people who were looking to change their careers and Dan and I sat down with each of them. None ended up applying for various reasons but we hoped she would send us more candidates.

Who is Rubba? I would be very happy to have the opportunity to meet with Reem/anyone from her office again. In our last email, she suggested coordinating a visit of 9 Rayan managers to FAC - but when Esraa and I followed up, she was unavailable for a long period of time. 

Would you like to reach out and find out if she would be available to meet sometime during the week of the 2nd when Dan and I are in Nazareth?

**Comment by HilbertSpitzer** [comment]
> Dona Haj from the UKITH connected us to Reem Zoaby last December

So it's been half a year since anyone got in touch with her?

> I would be very happy to have the opportunity to meet with Reem/anyone from her office again

I can't guarantee that, but at least please prepare for me something to say to her, I'm fairly certain I can meet her eye-to-eye for a few minutes but she's not the kind of person I can sit with for hours on end as though there was no tomorrow like Rubba, nevermind messaging her at 0:58 with unreasonable demands and yet getting an immediate good reply anyway. Suffice to say, this won't be as easy of a thing to do, so caution please

> In our last email, she suggested coordinating a visit of 9 Rayan managers to FAC - but when Esraa and I followed up, she was unavailable for a long period of time.

I'm not sure what to make of this

> Would you like to reach out and find out if she would be available to meet sometime during the week of the 2nd when Dan and I are in Nazareth?

First of all, do you actually need my help with this? Because I'm getting the impression that I'm not very needed here. If you do need help then I need a coupe of things:
- What does 2nd week mean? From 9 July to 16 July? When? Where?
- What do you want me to say to her?
- Are we **absolutely sure** that we're talking about the same person here? For example, [is this the person you're talking about?](http://cdn.timesofisrael.com/uploads/2016/03/reem-rayan.jpg) One site describes her like this: "Reem Zoabi Abu Ishak is the director of Nazareth’s Riyan Employment Center – one of 21 employment centers established in Arab society through Al Fanar, via a strategic collaboration between the Israeli government, JDC-Tevet and Yad Hanadiv Rothschild Foundation."

**Comment by rebeccaradding** [comment]
@HilbertSpitzer 

1. Week of July 2, on Monday/Tuesday/Wednesday
1. Yes, your personal connection to her would be very helpful
1. I am certain we are talking about the same person

**Comment by HilbertSpitzer** [comment]
Alright, so what do you want me to tell her? To meet with you on July 2/3/4? At what times and where and what will you be discussing?
Should I tell her to call back Esraa?(what phone number did he use to call her?)

**Comment by HilbertSpitzer** [comment]
Alright, so the wife of Reem Zoabi brother says that she will inform her of what you told me and says that Reem Zoabi was unresponsive because she was too busy moving to a new house. If all goes well then soon enough she will contact either someone related to me or @esraajb himself or anyone who's contacted her before from FAC really

So yeah, that's the report for now

**Comment by HilbertSpitzer** [comment]
Double update: ok, I have confirmed that Reem Zoabi has been informed, @esraajb , or whoever else she was in contact with, be prepared

**Comment by Heathercoraje** [comment]
@esraajb Did you ever hear from Reem Zoabi?

**Comment by esraajb** [comment]
@Heathercoraje meeting her tomorrow

**Comment by Heathercoraje** [comment]
@esraajb Let @sajedazoabi and I know if there is anything we could help.

**Comment by esraajb** [comment]
I met Reem today(July 10th). 
She seemed nice and willing to help.

Things we discussed: 
* How she can help us with applicants.
Our action points: 
1) send her a profile of the people we are looking for. A general profile where she can decide who from the people she has can do our course.
2) Send her Info about the course and the pre-course
3) What are the opportunities our graduate have
after we send her all of that, I might go to their offices and talk about F&C in front of everyone in there, so they know what to say about us. or they will come here(to FAC).

* English Course. 
They can provide English course. We should have a list of people, who wants to do the course, what is their level. She is going to research what kind of English course they can offer.

* Empowerment for our local students:
1) prepare them for interviews.
2) give them confidence and what is the best way to introduce themselves.

* An evening/weekend course.
They have money to fund a course that runs in the evenings/weekends.
Our action point:
Send her a detailed plan which includes:
1) what we do in the course
2) how long it takes
3) costs
4) how the students benefit from it
5) how good are the chances to find a job after you finish the course

**Comment by rebeccaradding** [comment]
Moving conversation to `nazareth-programme`, closing issue here.

https://github.com/foundersandcoders/nazareth-programme/issues/200
